# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: AmperVolt
      MYSQL_ROOT_PASSWORD: q1w2e3r4
    ports:
      - 33061:3306
